apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# namespace: tenants-

commonLabels:
  someName: someValue
  owner: alice
  app: bingo
  
commonAnnotations:
  app: annotation1


resources:
- deployment.yaml
- service.yaml
